### ISSUE TITLE
能不能在配置文件里自定义mathjax输出类型和括号啊

### ISSUE THREAD

**Issue by lolifamily** [next-theme/hexo-filter-mathjax#20]

**Comment by stevenjoezhang** [comment]
可能可以实现，但比较困难。这个插件实际上是 hack 了 mathjax 的内部 API，如果改动比较多的话会存在兼容问题。
我有时间会研究一下，但仍然建议在文章内通过 mathjax 提供的指令进行设置。

**Comment by lolifamily** [comment]
为什么要用mathjax-full啊？直接用mathjax不可以吗？

**Comment by stevenjoezhang** [comment]
不可以，`mathjax` 是 `mathjax-full` 的真子集。直接用 `mathjax` 会导致中文字符宽度错误、`<!-- more -->` 失效等一系列问题。
