### ISSUE TITLE
_config.mathjax.append_css

### ISSUE THREAD

**Issue by awnawnawn** [next-theme/hexo-filter-mathjax#24]
append_css is set to true, all pages are rendered <style>,
even if the post of MathJax is not used <style> is rendered. Can it be optimized?
With MathJax enabled in the post to decide whether to render <style>

**Comment by stevenjoezhang** [comment]
Thanks for your suggestion. Fixed in https://github.com/next-theme/hexo-filter-mathjax/commit/f6c7d7e3ed9c28325a214ae1f43c4d1b2edd540c

**Comment by awnawnawn** [comment]
It still doesn't seem to work. If both are set to false, css will not be loaded. Do not load css even if the article sets mathjax to true
------------------------------------------------
![Snipaste_2020-09-24_05-08-18](https://user-images.githubusercontent.com/47672657/94070114-3df58600-fe24-11ea-947e-322f15cadd5d.png)
![Snipaste_2020-09-24_05-06-53](https://user-images.githubusercontent.com/47672657/94070119-40f07680-fe24-11ea-9347-b21b1243c9ad.png)
![Snipaste_2020-09-24_05-07-25](https://user-images.githubusercontent.com/47672657/94070126-43eb6700-fe24-11ea-9061-821f39c0827f.png)

**Comment by stevenjoezhang** [comment]
Docs updated: https://github.com/next-theme/hexo-filter-mathjax/commit/1de71bd9489db5806c25f0d57964674d93c638d0

**Comment by awnawnawn** [comment]
在home页也加载到了渲染出来了<style>，是不是再加个is_post()来判断呢

**Comment by stevenjoezhang** [comment]
home 页需要加载 style，否则文章摘要中的数学公式显示不正确

**Comment by awnawnawn** [comment]
有个问题想请教下，我`hexo`使用的是默认装有的`prismjs`代码高亮，我在里边看到了有个`copy`的插件，但是我不知道如何启用这个插件，您知道么
![Snipaste_2021-01-06_01-12-56](https://user-images.githubusercontent.com/47672657/103677130-df13e100-4fbc-11eb-9f7b-30674f4f3c6d.jpg)

**Comment by stevenjoezhang** [comment]
您好，Hexo 只集成了 prismjs 的基础功能，并没有包含代码复制插件。必须要 Hexo 主题支持，才能使用这一功能。

**Comment by awnawnawn** [comment]
您好，我目前在写hexo模板主题，我应该如果修改呢或者调用呢，第一次接触这个。

**Comment by stevenjoezhang** [comment]
prismjs 的代码复制需要在前端加载三个 js 和一个 css：
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/toolbar/prism-toolbar.css">
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/components/prism-core.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/toolbar/prism-toolbar.js"></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/copy-to-clipboard/prism-copy-to-clipboard.js"></script>
```

**Comment by awnawnawn** [comment]
您好，添加后有按钮了也可以使用，但似乎和hexo集成的冲突了，代码的样式和行号不渲染出来了

**没有添加**
![1](https://user-images.githubusercontent.com/47672657/103732538-8ecf6a00-5022-11eb-8498-05349b706382.jpg)

**添加后**
![2](https://user-images.githubusercontent.com/47672657/103732551-968f0e80-5022-11eb-945f-28a4345ab58e.jpg)

**Comment by stevenjoezhang** [comment]
在 Hexo `_config.yml` 中禁用 `prismjs.preprocess`:
```yml
prismjs:
  enable: true
  preprocess: false
  line_number: true
  tab_replace: ''
```

**Comment by awnawnawn** [comment]
我设置为false了，也不行
