### ISSUE TITLE
Do not start a new line when adding formula blocks

### ISSUE THREAD

**Issue by chnynf** [next-theme/hexo-filter-mathjax#39]
Is it possible to let the formula block stay in the existing line?

For example, when I have this in markdown:

`This is a formula $$a+b=c$$. `

It's still rendered as:

```
This is a formula
a+b=c
```

Am I doing something wrong here?

**Comment by stevenjoezhang** [comment]
Use single dollars:
```
This is a formula $a+b=c$.
```
