### ISSUE TITLE
分段函数的问题

### ISSUE THREAD

**Issue by 15874330629** [next-theme/hexo-filter-mathjax#48]
![image](https://user-images.githubusercontent.com/52911891/162359522-175fa6e7-69bf-4639-9354-d8533b2f4342.png)
![image](https://user-images.githubusercontent.com/52911891/162359555-da57c15c-da65-4ea6-b0af-6f34d2e58e49.png)
是我的语法有问题吗？还是，很不理解，很影响使用体验

**Comment by stevenjoezhang** [comment]
部分 Markdown 渲染插件会将 `\\` 转义为 `\`，因此想要输出 `\\` 需要写 `\\\\`
