### ISSUE TITLE
physics宏包支持

### ISSUE THREAD

**Issue by ZJY0516** [next-theme/hexo-filter-mathjax#52]
``` 
 extension_options: {}
    # you can put your extension options here
    # see http://docs.mathjax.org/en/latest/options/input/tex.html#tex-extension-options for more detail
```
我想加入`physics`宏包，但是我没有搞懂应该如何填写配置文件，请问能否给出一个示例。

**Comment by stevenjoezhang** [comment]
试试这样
```yml
mathjax:
  extension_options:
    packages: {'[+]': ['physics']}
```

**Comment by ZJY0516** [comment]
按照上面所说加载了`physics`宏包后，默认加载的的那些宏包消失了。
$\LaTeX$代码如下：
```
$$
\dd{(x^2)}=2x \dd{x}
$$

$$
\bra{\psi} \quad \ket{\psi}
$$

$$
\laplacian{\Psi} \quad \curl{\vb{a}} \quad \div{\vb{a}} \quad \grad{\Psi}
$$

$$
\begin{vmatrix}
1 & 2\\
3 & 4\\
\end{vmatrix}
$$

$$
\verb|\sqrt|
$$
```
其中第一个和第三个为`physics`宏包支持的功能，第二个为`braket`和`physics`宏包共有的功能，第四个为`ams`宏包的功能，第五个为`verb`宏包的功能。
在没有修改`extension_options`时渲染结果如下
![image](https://user-images.githubusercontent.com/86695626/180928445-9c8f03e5-4d7b-46fe-ad94-e91726670a28.png)
加载`physics`宏包后只有一、二、三行可以正常渲染。
![image](https://user-images.githubusercontent.com/86695626/180928653-7560fd72-be9d-4cb1-8768-bfc9da5e8bc2.png)
我的猜测：是否应该同时加载`physics`和`autoload`。
如果是这样，请问能否给出一个同时加载两个宏包的示例。

**Comment by stevenjoezhang** [comment]
我修改了一下： https://github.com/next-theme/hexo-filter-mathjax/commit/c752ffacead3336c220a2b2d358713efeb0f5e09
您也照着这个 commit 改改 `lib/filter.js` （也就是 Hexo 目录下的 `node_modules/hexo-filter-mathjax/lib/filter.js`），然后这样设置
```yml
mathjax:
  packages:
    - physics
```

**Comment by ZJY0516** [comment]
可以了！感谢！！Thanks♪(･ω･)ﾉ
