### ISSUE TITLE
tikzjax

### ISSUE THREAD

**Issue by mathirst** [next-theme/hexo-filter-mathjax#56]
Hello,

Thanks for your nice plug-in. I am wondering whether it could support tikzjax or not. If so, how to make it?

**Comment by stevenjoezhang** [comment]
Do you mean this tikzjax: https://github.com/kisonecat/tikzjax
I'm afraid it may not be supported. TikZJax is TikZ running under WebAssembly in the browser, but this plugin runs server-side.
See also https://github.com/mathjax/MathJax/issues/41

**Comment by mathirst** [comment]
> Do you mean this tikzjax: https://github.com/kisonecat/tikzjax I'm afraid it may not be supported. TikZJax is TikZ running under WebAssembly in the browser, but this plugin runs server-side. See also [mathjax/MathJax#41](https://github.com/mathjax/MathJax/issues/41)

I see. Thank you!

**Comment by stevenjoezhang** [comment]
And, you can try to use tikzjax like this in Hexo:

```md
---
title: LaTeX demo
date: 2022-11-22 16:33:13
mathjax: true
---

<link rel="stylesheet" type="text/css" href="https://tikzjax.com/v1/fonts.css">
<script src="https://tikzjax.com/v1/tikzjax.js"></script>
<script type="text/tikz">
  \begin{tikzpicture}
    \draw (0,0) circle (1in);
  \end{tikzpicture}
</script>
```

this plugin won't render math formulas inside `<script>` tag, so the front-end script of tikzjax can handle them when users open the webpage

**Comment by prinsss** [comment]
In case anyone is still interested in using TikZJax in Hexo, I have created a new plugin for server side TikZ rendering, which internally runs TikZJax on Node.js.

See: [hexo-filter-tikzjax](https://github.com/prinsss/hexo-filter-tikzjax)

**Comment by stevenjoezhang** [comment]
@prinsss Is hexo-filter-tikzjax compatible with hexo-filter-mathjax? I can add a link in README

**Comment by prinsss** [comment]
> @prinsss Is hexo-filter-tikzjax compatible with hexo-filter-mathjax? I can add a link in README

Yes, it is. Here is a working demo: [StackBlitz](https://stackblitz.com/edit/hexo-mathjax-tikzjax?file=source%2F_posts%2Ftikz-test.md).

I'm using hexo-filter-mathjax + hexo-filter-tikzjax + pandoc in [my own blog](https://github.com/prinsss/prinsss.github.io/blob/source/package.json#L12) and it works pretty well. It would be appreciated if this could help more people with similar needs. :)
