### ISSUE TITLE
百分号不渲染

### ISSUE THREAD

**Issue by xuehuasu** [next-theme/hexo-filter-mathjax#65]
我确定markdown中其它数学公式都正常显示，直到遇到百分号：
当渲染到%时，当前公式就被中断，比如：
$$
gcd(a,b)=gcd(b,a\%b)
$$
正常渲染是这样：
![image](https://github.com/next-theme/hexo-filter-mathjax/assets/81012806/4200fbf8-aae3-4684-8c8c-a24d8aaee790)
hexo是这样：
![image](https://github.com/next-theme/hexo-filter-mathjax/assets/81012806/aa9de2f8-0bc8-4f00-b591-918c07bfaa89)

更复杂一点的：
$$
(\frac{a}{b}\%m)=(\frac{a}{b}\%m)*bk\%m=ak\%m
$$
正常渲染是这样：
![image](https://github.com/next-theme/hexo-filter-mathjax/assets/81012806/25992706-0daa-41b8-8311-bbf48ecb3406)
hexo也在%卡住了：
![image](https://github.com/next-theme/hexo-filter-mathjax/assets/81012806/5f7206a6-870b-40f8-9b7d-5ea54d638fb5)

**Comment by stevenjoezhang** [comment]
百分号是LaTeX里面的注释，我试了像xelatex这种引擎也是不渲染的。
你可以尝试进行转义，把`%`替换为`\%`或者`\\%`应该就行了
